steps:
- name: 'hashicorp/terraform:latest'
  id: 'tf-init'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd terraform
      terraform init
- name: 'hashicorp/terraform:latest'
  id: 'tf-apply'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd terraform
      terraform apply -auto-approve
