# cloudbuild.yaml

substitutions:
  # ← replace 1234567 with your real GitHub App installation ID,
  # or set this in your trigger’s substitution settings.
  _APP_INSTALLATION_ID: "77558712"

options:
  # required when you pin a custom build.service_account
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/github-pat/versions/latest"
      env: "GITHUB_PAT"
steps:
  - name: hashicorp/terraform:latest
    args: ["init","-input=false"]
  - name: hashicorp/terraform:latest
    args: ["apply","-auto-approve","-input=false"]
