# cloudbuild.yaml

substitutions:
  # ← replace 1234567 with your real GitHub App installation ID,
  # or set this in your trigger’s substitution settings.
  _APP_INSTALLATION_ID: "77558712"

options:
  # required when you pin a custom build.service_account
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/github-pat/versions/latest"
      env: "GITHUB_PAT"

steps:
  # ─────────────────────────────────────────────────────────────
  # 1) Terraform Init
  - id: tf-init
    name: "hashicorp/terraform:latest"
    secretEnv: ["GITHUB_PAT"]
    env:
      # inject your PAT and App ID as TF_VARs
      - "TF_VAR_github_pat=$$GITHUB_PAT"
      - "TF_VAR_app_installation_id=$_APP_INSTALLATION_ID"
    # disable interactive prompts
    args: ["init","-input=false"]

  # ─────────────────────────────────────────────────────────────
  # 2) Terraform Apply
  - id: tf-apply
    name: "hashicorp/terraform:latest"
    secretEnv: ["GITHUB_PAT"]
    env:
      - "TF_VAR_github_pat=$$GITHUB_PAT"
      - "TF_VAR_app_installation_id=$_APP_INSTALLATION_ID"
    args: ["apply","-auto-approve","-input=false"]

  # ─────────────────────────────────────────────────────────────
  # 3) Build your Docker image
  - id: docker-build
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA"
      - "."

  # ─────────────────────────────────────────────────────────────
  # 4) Push the image
  - id: docker-push
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA"

  # ─────────────────────────────────────────────────────────────
  # 5) Deploy to Cloud Run
  - id: run-deploy
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy python-service-649439655037 \
          --image=gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --project=double-genius-466920-b8 \
          --allow-unauthenticated

images:
  - "gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA"
