options:
  logging: CLOUD_LOGGING_ONLY   # if you’re using a custom serviceAccount

steps:
# — Terraform Init —
- id: tf-init
  name: "hashicorp/terraform:latest"
  # Make the secret available as $GITHUB_PAT
  secretEnv: ["GITHUB_PAT"]
  # Tell Terraform to use the env var as a TF_VAR
  env:
    - "TF_VAR_github_pat=$$GITHUB_PAT"
  args: ["init"]

# — Terraform Apply —
- id: tf-apply
  name: "hashicorp/terraform:latest"
  secretEnv: ["GITHUB_PAT"]
  env:
    - "TF_VAR_github_pat=$$GITHUB_PAT"
  args: ["apply","-auto-approve"]

# … then your Docker build/push and Cloud Run deploy steps …
# (omitted for brevity)
availableSecrets:
  secretManager:
  - versionName: "projects/$PROJECT_ID/secrets/github-pat/versions/latest"
    env: "GITHUB_PAT"
