# cloudbuild.yaml

options:
  logging: CLOUD_LOGGING_ONLY       # satisfy custom-SA → logging requirement

steps:
  # 1) terraform init (in root, where your .tf files are)
  - id: tf-init
    name: "hashicorp/terraform:latest"
    # removed dir: , so defaults to /workspace
    args: ["init"]

  # 2) terraform apply
  - id: tf-apply
    name: "hashicorp/terraform:latest"
    args: ["apply", "-auto-approve"]

  # 3) build & push your container
  - id: docker-build
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA"
      - "."

  - id: docker-push
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA"

  # 4) deploy to Cloud Run
  - id: run-deploy
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy python-service-649439655037 \
          --image gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA \
          --region us-central1 \
          --platform managed \
          --project double-genius-466920-b8 \
          --allow-unauthenticated

images:
  - "gcr.io/$PROJECT_ID/resume-backend:$SHORT_SHA"
